# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.4'

gem 'jekyll-minifier', '~> 0.2'
gem 'jekyll-seo-tag', '~> 2.2'
gem 'jekyll-sitemap', '~> 1'

gem 'base64', '~> 0.3'

gem 'kramdown-parser-gfm'

gem 'webrick', '~> 1.8'
